untitled777/urls.py
from django.contrib import admin
from django.urls import path
from prostyling import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('recall', views.recall, name='recall'),
    path('reviews', views.reviews, name='reviews'),
    path('works', views.works, name='works'),
    path('work/<int:raboti_id>', views.works_detail, name='works_detail'),
    path('rev_add', views.rev_add, name='rev_add'),
    path('detailing_car_wash', views.detailing_car_wash, name='detailing_car_wash'),
    path('detailing_motor_wash', views.detailing_motor_wash, name='detailing_motor_wash'),
    path('polirovka_kuzova', views.polirovka_kuzova, name='polirovka_kuzova'),
    path('pokritie_keramica', views.pokritie_keramica, name='pokritie_keramica'),
    path('pokritie_steklo', views.pokritie_steklo, name='pokritie_steklo'),
    path('pokritie_antidojd', views.pokritie_antidojd, name='pokritie_antidojd'),
    path('polirovka_optiki', views.polirovka_optiki, name='polirovka_optiki'),
    path('himchistka', views.himchistka, name='himchistka'),
    path('zashchitnye_pokrytiya_leather', views.zashchitnye_pokrytiya_leather, name='zashchitnye_pokrytiya_leather'),
    path('zashchitnye_pokrytiya_tex', views.zashchitnye_pokrytiya_tex, name='zashchitnye_pokrytiya_tex'),
    path('polirovka_interier', views.polirovka_interier, name='polirovka_interier'),
    path('ozonirovanie', views.ozonirovanie, name='ozonirovanie'),
    path('add_raboty', views.add_raboty, name='add_raboty'),
    path('login_to', views.login_to, name='login_to'),
    path('test', views.test, name='test'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prostyling/models.py
from django.db import models
from django.dispatch import receiver
# Create your models here.
from django.db.models.signals import post_delete


class carusel(models.Model):
    number = models.IntegerField()
    photo = models.ImageField(upload_to ='carusel/')

@receiver(post_delete, sender=carusel)
def submission_delete(sender, instance, **kwargs):
    instance.photo.delete(False)

class otziv(models.Model):
    author_name = models.CharField(max_length=50)
    text = models.CharField(max_length=500)
    date = models.CharField(max_length=20, default='')
    rating = models.IntegerField(default=0)
    moderate = models.BooleanField(default=False)
    comment = models.CharField(max_length=500 ,default='')


class raboti(models.Model):
    opisanie = models.CharField(max_length=100)
    text = models.TextField()
    date = models.CharField(max_length=20)

class raboti_photo(models.Model):
    photo_raboti = models.ForeignKey(raboti, on_delete=models.CASCADE, blank=True)
    photo = models.ImageField(upload_to='photos/', blank=True)

@receiver(post_delete, sender=raboti_photo)
def submission_delete(sender, instance, **kwargs):
    instance.photo.delete(False)

class test_model(models.Model):
    name = models.CharField(max_length=100)
    balance = models.IntegerField(default=0)

templates/add_raboty.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    {% if user.is_authenticated %}
        <div class="container">
        <h1>Добавить новую работу</h1>
            <form action="{% url 'add_raboty' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Описание</label>
                    <input name="opisanie" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Текст</label>
                     <textarea name="text" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Дата</label>
                    <input name="date" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
              <h3>Фото</h3>
                <div class="custom-file mb-3">
                  <input name="photos" type="file" class="custom-file-input" id="customFile" multiple>
                  <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
        
    {% else %}
        <div class="container">
        <h3>Вход</h3>
            <form method="post" action="{% url 'login_to' %}">
                {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input name="username" type="tel" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    {% endif %} 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/detailing_car_wash.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    Детейлинг мойка автомобиля
{% endblock %}
{% block meta_desc %}
        <meta name="description" content="Детейлинг мойка автомобиля, трех фазная мойка" />
{% endblock %}
{% block content %}
    {% if messages %}

        {% for message in messages %}
            <button hidden type="button" id="quikzapis-recall" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter1">
              Launch demo modal
            </button>

            <div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 aria-invalid="zapis-title" class="modal-title" id="zapis-title">Заявка отправлена</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body" id="zapis-body">
                        <h3>Ваша заявка отправлена, менеджер вам перезвонит в ближайшее время для уточнения информации!</h3>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
    {% endif %}

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'index' %}#services">Услуги</a></li>
            <li class="breadcrumb-item active" aria-current="page">Детейлинг мойка</li>
          </ol>
        </nav>

    <div class="container">
        <h1>Детейлинг мойка автомобиля</h1>
        <hr>
        <h4>Привести авто в идеальный порядок позволяет детейлинг мойка автомобиля, осуществляемая с применением специальных инновационных средств.</h4>
        <hr>
        <img class="img-fluid" src="{% static 'moyka_usluga.jpg' %}" alt="">

        <table class="table table-bordered mt-5">
          <thead>
            <tr>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Kia Picanto, Hyundai Getz, Ford Fiesta, Chevrolet Spark, Citroen C1, C2c, Daewoo Matiz, Peugeot 107, 108">
                  1 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Kia Rio Ceed, Hyundai Solaris, Skoda Fabia, BMW 1-3, Audi a1-a4">
                  2 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Skoda Octavia, Superb, BMW 4 5, X1-X4, Toyota Rav-4, Kia Sportage">
                  3 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="BMW 7 series, X5-X7, Range-Rover, Cadillac Escalade">
                  4 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Mercedes-Benz Viano, Sptinter , Ford Trasit">
                  5 класс
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colspan="3">1000р</td>
              <td colspan="2">1500р</td>
            </tr>
          </tbody>
        </table>

        <h4>
            Начинается все с трехфазной мойки, первым этапом осуществляется бесконтактная мойка кузова. На кузов автомобиля наносится специальный высококонцентрированный щелочной состав для бесконтактной мойки, мы используем Detail AS «Active Safe».Он необходим для очистки кузова автомобиля от основных загрязнений: под его воздействием происходит отделение прилипшей грязи, птичьего помёта и следов насекомых.
            <br>
            <br>
            Следующий этап детейлинг мойки — ручная мойка.
            Применяется концентрированный шампунь (мы используем Detail SP «Second Phase»), предназначенный для бережной и тщательной очистки кузова автомобиля.
            Он абсолютно безопасен для хрома и, благодаря своему составу, полностью нейтрализует щелочь от предыдущего состава.
            <br>
            <br>
            На третьем этапе Кузов автомобиля покрывается консервирующим воском leraton C3. Данный воск образует защитную пленку на поверхности ЛКП, которая обеспечивает длительное сохранение зеркального блеска и, помимо этого, обеспечивает дополнительный гидрофобный эффект, благодаря которому высушить автомобиль становится значительно легче.
            <br>
            <br>
            Заключительным этапом детейлинг-мойки является сушка кузова автомобиля, которая осуществляется при помощи специальной двухтурбинной сушилки и микрофибровых полотенец.
        </h4>

        <h1 class="mt-3">Заявка на прием автомобиля</h1>
        <form class="mb-5" action="{% url 'detailing_car_wash' %}" method="post">
                    {% csrf_token %}
                      <div class="form-group">
                        <label for="perezvon_name">Имя</label>
                        <input name="perezvon_name" type="text" class="form-control" id="perezvon_name" aria-describedby="emailHelp">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Номер телефона</label>
                        <input name="perezvon_phone" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Марка и модель авто</label>
                        <input name="perezvon_car" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <input name="perezvon_sluga" type="text" hidden value="Детейлинг мойка кузова">

                      <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>


{% endblock %}

{% block scripts %}
    <script>
        $(function () {
          $('[data-toggle="popover"]').popover()
        })
    </script>
{% endblock %}

templates/detailing_motor_wash.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    Детейлинг мойка моторного отсека
{% endblock %}
{% block meta_desc %}
        <meta name="description" content="Детейлинг мойка моторного отсека" />
{% endblock %}
{% block content %}
    {% if messages %}

        {% for message in messages %}
            <button hidden type="button" id="quikzapis-recall" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter1">
              Launch demo modal
            </button>

            <div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 aria-invalid="zapis-title" class="modal-title" id="zapis-title">Заявка отправлена</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body" id="zapis-body">
                        <h3>Ваша заявка отправлена, менеджер вам перезвонит в ближайшее время для уточнения информации!</h3>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
    {% endif %}

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'index' %}#services">Услуги</a></li>
            <li class="breadcrumb-item active" aria-current="page">Детейлинг мойка моторного отсека</li>
          </ol>
        </nav>

    <div class="container">
        <h1>Детейлинг мойка моторного отсека</h1>
        <hr>
        <h4>
            Мы предлагаем безопасную мойку двигателя по современной технологии, предохраняющей двигатель и подкапотную проводку автомобиля от повреждений.
        </h4>
        <hr>
        <img class="img-fluid" src="{% static 'moika_motorajpeg.jpeg' %}" alt="">

        <table class="table table-bordered mt-5">
          <thead>
            <tr>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Kia Picanto, Hyundai Getz, Ford Fiesta, Chevrolet Spark, Citroen C1, C2c, Daewoo Matiz, Peugeot 107, 108">
                  1 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Kia Rio Ceed, Hyundai Solaris, Skoda Fabia, BMW 1-3, Audi a1-a4">
                  2 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Skoda Octavia, Superb, BMW 4 5, X1-X4, Toyota Rav-4, Kia Sportage">
                  3 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="BMW 7 series, X5-X7, Range-Rover, Cadillac Escalade">
                  4 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Mercedes-Benz Viano, Sptinter , Ford Trasit">
                  5 класс
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colspan="3">от 2500р</td>
              <td colspan="2">от 3000р</td>
            </tr>
          </tbody>
        </table>

        <h4>
            Мойка двигателя автомобиля, как и подкапотного пространства в целом, преследует как эстетические, так и вполне практические цели.
            <br>
            <br>
            Загрязнённое подкапотное пространство — это не только некрасиво, но и вредит системам автомобиля: грязь может попасть в воздушный фильтр и технические жидкости, что приводит к преждевременному износу двигателя и других агрегатов. Шланги и электропроводка, покрытые слоем грязи, разрушаются и трескаются.

            <br>
            <br>

        </h4>

        <h1 class="mt-3">Заявка на прием автомобиля</h1>
        <form class="mb-5" action="{% url 'detailing_motor_wash' %}" method="post">
                    {% csrf_token %}
                      <div class="form-group">
                        <label for="perezvon_name">Имя</label>
                        <input name="perezvon_name" type="text" class="form-control" id="perezvon_name" aria-describedby="emailHelp">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Номер телефона</label>
                        <input name="perezvon_phone" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Марка и модель авто</label>
                        <input name="perezvon_car" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <input name="perezvon_sluga" type="text" hidden value="Детейлинг мойка моторного отсека">

                      <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>


{% endblock %}

{% block scripts %}
    <script>
        $(function () {
          $('[data-toggle="popover"]').popover()
        })
    </script>
{% endblock %}

templates/himchistka.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    Детейлинг химчистка салона
{% endblock %}
{% block meta_desc %}
        <meta name="description" content="Детейлинг химчистка салона" />
{% endblock %}
{% block content %}
    {% if messages %}

        {% for message in messages %}
            <button hidden type="button" id="quikzapis-recall" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter1">
              Launch demo modal
            </button>

            <div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 aria-invalid="zapis-title" class="modal-title" id="zapis-title">Заявка отправлена</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body" id="zapis-body">
                        <h3>Ваша заявка отправлена, менеджер вам перезвонит в ближайшее время для уточнения информации!</h3>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
    {% endif %}

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'index' %}#services">Услуги</a></li>
            <li class="breadcrumb-item active" aria-current="page">Детейлинг химчистка салона</li>
          </ol>
        </nav>

    <div class="container">
        <h1>Детейлинг химчистка салона</h1>
        <hr>
        <h4>
            Профессиональная детейлинг химчистка салона автомобиля: полная очистка кожи и текстиля сидений, руля, потолка, багажника от любых загрязнений.
        </h4>
        <hr>
        <img class="img-fluid" src="{% static 'polirovka_usluga.jpg' %}" alt="">

        <table class="table table-bordered mt-5">
          <thead>
            <tr>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Kia Picanto, Hyundai Getz, Ford Fiesta, Chevrolet Spark, Citroen C1, C2c, Daewoo Matiz, Peugeot 107, 108">
                  1 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Kia Rio Ceed, Hyundai Solaris, Skoda Fabia, BMW 1-3, Audi a1-a4">
                  2 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Skoda Octavia, Superb, BMW 4 5, X1-X4, Toyota Rav-4, Kia Sportage">
                  3 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="BMW 7 series, X5-X7, Range-Rover, Cadillac Escalade">
                  4 класс
              </th>
              <th scope="col"  data-container="body" data-toggle="popover" data-placement="top" data-content="Mercedes-Benz Viano, Sptinter , Ford Trasit">
                  5 класс
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>от 2000р</td>
              <td>от 2500р</td>
              <td>от 3000р</td>
              <td>от 4000р</td>
              <td>от 5000р</td>
            </tr>
          </tbody>
        </table>

        <h4>
            Все поверхности салона автомобиля в меньшей или большей степени подвержены скоплению пыли, впитыванию грязи, жира и неприятных запахов, но самое вредное и опасное — скопление вредоносных бактерий, в том числе вызывающих аллергию и другие заболевания.
            <br>
            <br>
            Химчистку салона автомобиля рекомендуется проводить не реже одного-двух раз в году.
            Особенно это актуально для владельцев авто со светлым салоном.
            <br>
            <br>
            Безусловно, главная цель чистки салона – убрать видимые загрязнения и освежить внешний вид. Комплексная химчистка справляется с этой задачей на “отлично”, очищая все труднодоступные места и обновляя внешние поверхности салона, потолка и сидений (вне зависимости от того, из какого материала они изготовлены). Наши мастера используют экологически чистые моющие средства и ароматизаторы, которые безопасны для человека и не вызывают аллергических реакций.
        </h4>

        <h1 class="mt-3">Заявка на прием автомобиля</h1>
        <form class="mb-5" action="{% url 'himchistka' %}" method="post">
                    {% csrf_token %}
                      <div class="form-group">
                        <label for="perezvon_name">Имя</label>
                        <input name="perezvon_name" type="text" class="form-control" id="perezvon_name" aria-describedby="emailHelp">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Номер телефона</label>
                        <input name="perezvon_phone" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Марка и модель авто</label>
                        <input name="perezvon_car" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <input name="perezvon_sluga" type="text" hidden value="Детейлинг химчистка салона">

                      <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>


{% endblock %}

{% block scripts %}
    <script>
        $(function () {
          $('[data-toggle="popover"]').popover()
        })
    </script>
{% endblock %}

templates/raboti.html
{% extends 'index.html' %}
{% load static %}
{% block css_scr %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}
{% block title %}
    Наша работа
{% endblock %}
{% block content %}



        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'works' %}">Наши работы</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ r.opisanie }}</li>
          </ol>
        </nav>

    <div class="container">
        <h1>{{ r.opisanie }}</h1>
        <p>{{ r.date }} / Pro Styling /</p>
        <a data-fancybox="gallery" href="{{ r.raboti_photo_set.first.photo.url }}"><img class="img-fluid" src="{{ r.raboti_photo_set.first.photo.url }}"></a>
        <h5 class="mt-3 mb-3">{{ r.text }}</h5>
        <div class="row">
            {% for p in r.raboti_photo_set.all %}
                <div class="col-3">
                  <a data-fancybox="gallery" href="{{ p.photo.url }}"><img class="img-fluid" src="{{ p.photo.url }}"></a>
                </div>
            {% endfor %}
        </div>

        <h3 class="mt-3">Заявка на прием автомобиля</h3>
        <form class="mb-5" action="{% url 'recall' %}" method="post">
                    {% csrf_token %}
                      <div class="form-group">
                        <label for="perezvon_name">Имя</label>
                        <input name="perezvon_name" type="text" class="form-control" id="perezvon_name" aria-describedby="emailHelp">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Номер телефона</label>
                        <input name="perezvon_phone" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <div class="form-group">
                        <label for="perezvon_phone">Марка и модель авто</label>
                        <input name="perezvon_car" type="text" class="form-control" id="perezvon_phone">
                      </div>
                      <input name="perezvon_sluga" type="text" hidden value="Хочет детейлинг">

                      <button type="submit" class="btn btn-primary">Отправить</button>
        </form>

    </div>
{% endblock %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

templates/works.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
Наши работы
{% endblock %}
{% block content %}

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
        <li class="breadcrumb-item active" aria-current="page">Наши работы</li>
      </ol>
    </nav>

    <div class="container">
        <h1>Наши работы</h1>
        <div class="row">
              {% for r in raboti %}
                  <div class="col-12 col-lg-3 mt-3">
                    <div class="card">
                        <a style="color: black" href="{% url 'works_detail' r.id %}">
                            <img style="height: 200px" src="{{ r.raboti_photo_set.first.photo.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">{{ r.opisanie }}</h5>
                              <p class="card-text"><small class="text-muted">{{ r.date }}</small></p>
                            </div>
                        </a>
                    </div>
                  </div>
              {% endfor %}
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}